name: Feature Report
description: Request a feature for clover
labels: ["kind: feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking time to submit this report :D

        Before submitting feature report, please check the following, which may resolve your issue:
        * Have you checked that you are checking the latest versions of clover?
        * Have you [searched existing issues](https://github.com/hannbyul/clover/issues?q=is%3Aopen+is%3Aissue+label%3Akind%3A%20feature) to see if this feature has been requested before?

  - type: textarea
    attributes:
      label: Description
      description: Description of the desired feature.
    validations:
      required: true
