name: Vuln Report
description: Report a vulnerability in clover
labels: ["kind: vuln"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking time to submit this report :D

        Before submitting vuln report, please check the following, which may resolve your issue:
        * Have you checked that you are checking the latest versions of clover?
        * Have you [searched existing issues](https://github.com/hannbyul/clover/issues?q=is%3Aopen+is%3Aissue+label%3Akind%3A%20vuln) to see if this vulnerability has been reported before?

        **Important:** If this vulnerability is critical, please submit it privately.

  - type: textarea
    attributes:
      label: Description
      description: Description of vulnerability, with any relavant log messages or PoC.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps or Ideas to patch
      description: Steps or Ideas to patch vulnerability.

  - type: textarea
    attributes:
      label: Envrionment
      description: Some vulnerabilities are caused by problem with local environment settings. Before submitting, double-check your version of server and others.
